<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Reference -> https://classic.gazebosim.org/tutorials?tut=ros_gzplugins -->

  <xacro:property name="lidar_length" value="0.01" />
  <xacro:property name="lidar_radius" value="0.01" />


  <!-- we have to define link and joint -->

  <link name="lidar_link">
    <visual>
      <geometry>
        <cylinder length="${lidar_length}" radius="${lidar_radius}"/>
      </geometry>
      <material name="grey"/>
    </visual>

    <collision>
      <geometry>
        <cylinder length="${lidar_length}" radius="${lidar_radius}"/>
      </geometry>
    </collision>

    <xacro:cylinder_inertia m="0.1" radius="${lidar_radius}" length="${lidar_length}" xyz="0 0 0" rpy="0 0 0" />

  </link>


  <joint name="base_lidar_joint" type="fixed">
    <parent link="base_link"/>
    <child link="lidar_link"/>
    <origin xyz="${(0 / 2.0) } 0.0 ${base_height + lidar_length * 2.0}" rpy="0.0 0.0 0.0"/>
    <!-- <axis xyz="0.0 0.0 0.0"/> -->
  </joint>


  <gazebo reference="lidar_link">
    <material>Gazebo/Red</material>

    <sensor name="laser" type="ray">
      <pose> 0 0 0 0 0 0 </pose>
      <visualize>1</visualize>
      <update_rate>100</update_rate>
      <!-- <update_rate>1000</update_rate> -->
      <always_on>1</always_on>
      <ray>
        <scan>
          <horizontal>
            <!-- <samples>360</samples> -->
            <resolution>1</resolution>
            <samples>180</samples>
            <!-- <min_angle>${-3*pi/4.0}</min_angle>
            <max_angle>${3*pi/4.0}</max_angle> -->
            <min_angle>${-pi/2.0}</min_angle>
            <max_angle>${pi/2.0}</max_angle>
          </horizontal>
        </scan>
        <range>
          <min>0.3</min>
          <max>10.0</max>
          <resolution>0.01</resolution>
        </range>
      </ray>
      <plugin name="laser_controller" filename="libgazebo_ros_ray_sensor.so">
        <ros>
          <remapping>~/out:=scan</remapping>
        </ros>
        <output_type>sensor_msgs/LaserScan</output_type>
        <frame_name>lidar_link</frame_name>
      </plugin>
    </sensor>
  </gazebo>

</robot>