<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <gazebo reference="base_link">
    <material>Gazebo/Blue</material>
  </gazebo>

  <gazebo reference="left_wheel_link">
    <material>Gazebo/Grey</material>
  </gazebo>

  <gazebo reference="right_wheel_link">
    <material>Gazebo/Grey</material>
  </gazebo>

  <gazebo reference="caster_wheel_link">
    <material>Gazebo/Grey</material>
    <!-- these lines are about friction (coefficients) -->
    <mu1 value="0.1" />
    <mu2 value="0.1" />
  </gazebo>

  <!-- diff drive plugin -->
  <gazebo>
    <plugin name="diff_drive_controller" filename="libgazebo_ros_diff_drive.so">

      <!-- Update rate in Hz -->
      <update_rate>50</update_rate>

      <!-- wheels -->
      <left_joint>base_left_wheel_joint</left_joint>
      <right_joint>base_right_wheel_joint</right_joint>

      <!-- kinematics -->
      <wheel_separation>${base_width + wheel_length}</wheel_separation>
      <wheel_diameter>${wheel_radius * 2}</wheel_diameter>

      <!-- limits -->
      <max_wheel_torque>20</max_wheel_torque>
      <max_wheel_acceleration>1.8</max_wheel_acceleration>

      <!-- input -->
      <!-- send commands to this topic, robot node will listen to this topic -->
      <command_topic>cmd_vel</command_topic>

      <!-- output -->
      <publish_odom>true</publish_odom>
      <publish_odom_tf>true</publish_odom_tf>
      <publish_wheel_tf>true</publish_wheel_tf>

      <robotNamespace/>
      <always_on>1</always_on>

      <odometry_topic>odom</odometry_topic>
      <odometry_frame>odom</odometry_frame>
      <!-- <odometrySource>world</odometrySource> -->
      <robot_base_frame>base_footprint</robot_base_frame>

    </plugin>

  </gazebo>

</robot>
<!-- gazebo specific stuff -->